/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SicafRouteImport } from './routes/sicaf'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as CertidoesRouteImport } from './routes/certidoes'
import { Route as IndexRouteImport } from './routes/index'

const SicafRoute = SicafRouteImport.update({
  id: '/sicaf',
  path: '/sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CertidoesRoute = CertidoesRouteImport.update({
  id: '/certidoes',
  path: '/certidoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certidoes': typeof CertidoesRoute
  '/documentos': typeof DocumentosRoute
  '/missoes': typeof MissoesRoute
  '/sicaf': typeof SicafRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certidoes': typeof CertidoesRoute
  '/documentos': typeof DocumentosRoute
  '/missoes': typeof MissoesRoute
  '/sicaf': typeof SicafRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certidoes': typeof CertidoesRoute
  '/documentos': typeof DocumentosRoute
  '/missoes': typeof MissoesRoute
  '/sicaf': typeof SicafRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certidoes' | '/documentos' | '/missoes' | '/sicaf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certidoes' | '/documentos' | '/missoes' | '/sicaf'
  id: '__root__' | '/' | '/certidoes' | '/documentos' | '/missoes' | '/sicaf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertidoesRoute: typeof CertidoesRoute
  DocumentosRoute: typeof DocumentosRoute
  MissoesRoute: typeof MissoesRoute
  SicafRoute: typeof SicafRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sicaf': {
      id: '/sicaf'
      path: '/sicaf'
      fullPath: '/sicaf'
      preLoaderRoute: typeof SicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certidoes': {
      id: '/certidoes'
      path: '/certidoes'
      fullPath: '/certidoes'
      preLoaderRoute: typeof CertidoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertidoesRoute: CertidoesRoute,
  DocumentosRoute: DocumentosRoute,
  MissoesRoute: MissoesRoute,
  SicafRoute: SicafRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
