/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SicafRouteImport } from './routes/sicaf'
import { Route as ServicosIaRouteImport } from './routes/servicos-ia'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as LicitacoesRouteImport } from './routes/licitacoes'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ConcluidoRouteImport } from './routes/concluido'
import { Route as CertidoesRouteImport } from './routes/certidoes'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SicafRoute = SicafRouteImport.update({
  id: '/sicaf',
  path: '/sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIaRoute = ServicosIaRouteImport.update({
  id: '/servicos-ia',
  path: '/servicos-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesRoute = LicitacoesRouteImport.update({
  id: '/licitacoes',
  path: '/licitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcluidoRoute = ConcluidoRouteImport.update({
  id: '/concluido',
  path: '/concluido',
  getParentRoute: () => rootRouteImport,
} as any)
const CertidoesRoute = CertidoesRouteImport.update({
  id: '/certidoes',
  path: '/certidoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/certidoes': typeof CertidoesRoute
  '/concluido': typeof ConcluidoRoute
  '/documentos': typeof DocumentosRoute
  '/empresas': typeof EmpresasRoute
  '/licitacoes': typeof LicitacoesRoute
  '/missoes': typeof MissoesRoute
  '/pagamentos': typeof PagamentosRoute
  '/servicos': typeof ServicosRoute
  '/servicos-ia': typeof ServicosIaRoute
  '/sicaf': typeof SicafRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/certidoes': typeof CertidoesRoute
  '/concluido': typeof ConcluidoRoute
  '/documentos': typeof DocumentosRoute
  '/empresas': typeof EmpresasRoute
  '/licitacoes': typeof LicitacoesRoute
  '/missoes': typeof MissoesRoute
  '/pagamentos': typeof PagamentosRoute
  '/servicos': typeof ServicosRoute
  '/servicos-ia': typeof ServicosIaRoute
  '/sicaf': typeof SicafRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/certidoes': typeof CertidoesRoute
  '/concluido': typeof ConcluidoRoute
  '/documentos': typeof DocumentosRoute
  '/empresas': typeof EmpresasRoute
  '/licitacoes': typeof LicitacoesRoute
  '/missoes': typeof MissoesRoute
  '/pagamentos': typeof PagamentosRoute
  '/servicos': typeof ServicosRoute
  '/servicos-ia': typeof ServicosIaRoute
  '/sicaf': typeof SicafRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/certidoes'
    | '/concluido'
    | '/documentos'
    | '/empresas'
    | '/licitacoes'
    | '/missoes'
    | '/pagamentos'
    | '/servicos'
    | '/servicos-ia'
    | '/sicaf'
    | '/suporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/certidoes'
    | '/concluido'
    | '/documentos'
    | '/empresas'
    | '/licitacoes'
    | '/missoes'
    | '/pagamentos'
    | '/servicos'
    | '/servicos-ia'
    | '/sicaf'
    | '/suporte'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/certidoes'
    | '/concluido'
    | '/documentos'
    | '/empresas'
    | '/licitacoes'
    | '/missoes'
    | '/pagamentos'
    | '/servicos'
    | '/servicos-ia'
    | '/sicaf'
    | '/suporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  CertidoesRoute: typeof CertidoesRoute
  ConcluidoRoute: typeof ConcluidoRoute
  DocumentosRoute: typeof DocumentosRoute
  EmpresasRoute: typeof EmpresasRoute
  LicitacoesRoute: typeof LicitacoesRoute
  MissoesRoute: typeof MissoesRoute
  PagamentosRoute: typeof PagamentosRoute
  ServicosRoute: typeof ServicosRoute
  ServicosIaRoute: typeof ServicosIaRoute
  SicafRoute: typeof SicafRoute
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sicaf': {
      id: '/sicaf'
      path: '/sicaf'
      fullPath: '/sicaf'
      preLoaderRoute: typeof SicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos-ia': {
      id: '/servicos-ia'
      path: '/servicos-ia'
      fullPath: '/servicos-ia'
      preLoaderRoute: typeof ServicosIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes': {
      id: '/licitacoes'
      path: '/licitacoes'
      fullPath: '/licitacoes'
      preLoaderRoute: typeof LicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concluido': {
      id: '/concluido'
      path: '/concluido'
      fullPath: '/concluido'
      preLoaderRoute: typeof ConcluidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certidoes': {
      id: '/certidoes'
      path: '/certidoes'
      fullPath: '/certidoes'
      preLoaderRoute: typeof CertidoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  CertidoesRoute: CertidoesRoute,
  ConcluidoRoute: ConcluidoRoute,
  DocumentosRoute: DocumentosRoute,
  EmpresasRoute: EmpresasRoute,
  LicitacoesRoute: LicitacoesRoute,
  MissoesRoute: MissoesRoute,
  PagamentosRoute: PagamentosRoute,
  ServicosRoute: ServicosRoute,
  ServicosIaRoute: ServicosIaRoute,
  SicafRoute: SicafRoute,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
