/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SicafRouteImport } from './routes/sicaf'
import { Route as ServicosIaRouteImport } from './routes/servicos-ia'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProntidaoRouteImport } from './routes/prontidao'
import { Route as Pagamentos_naoefetuadoRouteImport } from './routes/pagamentos_naoefetuado'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicitacoesRouteImport } from './routes/licitacoes'
import { Route as FaltamRouteImport } from './routes/faltam'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ConcluidoRouteImport } from './routes/concluido'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as CertidoesRouteImport } from './routes/certidoes'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminSicafRouteImport } from './routes/admin.sicaf'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminPerfisRouteImport } from './routes/admin.perfis'
import { Route as AdminIaRouteImport } from './routes/admin.ia'
import { Route as AdminGoogleAdsRouteImport } from './routes/admin.google-ads'
import { Route as AdminFunilRouteImport } from './routes/admin.funil'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminDocumentosRouteImport } from './routes/admin.documentos'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminAutomacoesRouteImport } from './routes/admin.automacoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminAtendimentoRouteImport } from './routes/admin.atendimento'
import { Route as AdminAlertasRouteImport } from './routes/admin.alertas'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SicafRoute = SicafRouteImport.update({
  id: '/sicaf',
  path: '/sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIaRoute = ServicosIaRouteImport.update({
  id: '/servicos-ia',
  path: '/servicos-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntidaoRoute = ProntidaoRouteImport.update({
  id: '/prontidao',
  path: '/prontidao',
  getParentRoute: () => rootRouteImport,
} as any)
const Pagamentos_naoefetuadoRoute = Pagamentos_naoefetuadoRouteImport.update({
  id: '/pagamentos_naoefetuado',
  path: '/pagamentos_naoefetuado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesRoute = LicitacoesRouteImport.update({
  id: '/licitacoes',
  path: '/licitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaltamRoute = FaltamRouteImport.update({
  id: '/faltam',
  path: '/faltam',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcluidoRoute = ConcluidoRouteImport.update({
  id: '/concluido',
  path: '/concluido',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const CertidoesRoute = CertidoesRouteImport.update({
  id: '/certidoes',
  path: '/certidoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSicafRoute = AdminSicafRouteImport.update({
  id: '/sicaf',
  path: '/sicaf',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfisRoute = AdminPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoogleAdsRoute = AdminGoogleAdsRouteImport.update({
  id: '/google-ads',
  path: '/google-ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFunilRoute = AdminFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentosRoute = AdminDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomacoesRoute = AdminAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtendimentoRoute = AdminAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertasRoute = AdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/assistente': typeof AssistenteRoute
  '/certidoes': typeof CertidoesRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/concluido': typeof ConcluidoRoute
  '/documentos': typeof DocumentosRoute
  '/empresas': typeof EmpresasRoute
  '/faltam': typeof FaltamRoute
  '/licitacoes': typeof LicitacoesRoute
  '/login': typeof LoginRoute
  '/missoes': typeof MissoesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/pagamentos': typeof PagamentosRoute
  '/pagamentos_naoefetuado': typeof Pagamentos_naoefetuadoRoute
  '/prontidao': typeof ProntidaoRoute
  '/servicos': typeof ServicosRoute
  '/servicos-ia': typeof ServicosIaRoute
  '/sicaf': typeof SicafRoute
  '/suporte': typeof SuporteRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/atendimento': typeof AdminAtendimentoRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/automacoes': typeof AdminAutomacoesRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/funil': typeof AdminFunilRoute
  '/admin/google-ads': typeof AdminGoogleAdsRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/sicaf': typeof AdminSicafRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/assistente': typeof AssistenteRoute
  '/certidoes': typeof CertidoesRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/concluido': typeof ConcluidoRoute
  '/documentos': typeof DocumentosRoute
  '/empresas': typeof EmpresasRoute
  '/faltam': typeof FaltamRoute
  '/licitacoes': typeof LicitacoesRoute
  '/login': typeof LoginRoute
  '/missoes': typeof MissoesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/pagamentos': typeof PagamentosRoute
  '/pagamentos_naoefetuado': typeof Pagamentos_naoefetuadoRoute
  '/prontidao': typeof ProntidaoRoute
  '/servicos': typeof ServicosRoute
  '/servicos-ia': typeof ServicosIaRoute
  '/sicaf': typeof SicafRoute
  '/suporte': typeof SuporteRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/atendimento': typeof AdminAtendimentoRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/automacoes': typeof AdminAutomacoesRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/funil': typeof AdminFunilRoute
  '/admin/google-ads': typeof AdminGoogleAdsRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/sicaf': typeof AdminSicafRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/assistente': typeof AssistenteRoute
  '/certidoes': typeof CertidoesRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/concluido': typeof ConcluidoRoute
  '/documentos': typeof DocumentosRoute
  '/empresas': typeof EmpresasRoute
  '/faltam': typeof FaltamRoute
  '/licitacoes': typeof LicitacoesRoute
  '/login': typeof LoginRoute
  '/missoes': typeof MissoesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/pagamentos': typeof PagamentosRoute
  '/pagamentos_naoefetuado': typeof Pagamentos_naoefetuadoRoute
  '/prontidao': typeof ProntidaoRoute
  '/servicos': typeof ServicosRoute
  '/servicos-ia': typeof ServicosIaRoute
  '/sicaf': typeof SicafRoute
  '/suporte': typeof SuporteRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/atendimento': typeof AdminAtendimentoRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/automacoes': typeof AdminAutomacoesRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/funil': typeof AdminFunilRoute
  '/admin/google-ads': typeof AdminGoogleAdsRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/sicaf': typeof AdminSicafRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/assistente'
    | '/certidoes'
    | '/colaboradores'
    | '/concluido'
    | '/documentos'
    | '/empresas'
    | '/faltam'
    | '/licitacoes'
    | '/login'
    | '/missoes'
    | '/notificacoes'
    | '/pagamentos'
    | '/pagamentos_naoefetuado'
    | '/prontidao'
    | '/servicos'
    | '/servicos-ia'
    | '/sicaf'
    | '/suporte'
    | '/admin/alertas'
    | '/admin/atendimento'
    | '/admin/auditoria'
    | '/admin/automacoes'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/documentos'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/funil'
    | '/admin/google-ads'
    | '/admin/ia'
    | '/admin/perfis'
    | '/admin/relatorios'
    | '/admin/sicaf'
    | '/admin/suporte'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/assistente'
    | '/certidoes'
    | '/colaboradores'
    | '/concluido'
    | '/documentos'
    | '/empresas'
    | '/faltam'
    | '/licitacoes'
    | '/login'
    | '/missoes'
    | '/notificacoes'
    | '/pagamentos'
    | '/pagamentos_naoefetuado'
    | '/prontidao'
    | '/servicos'
    | '/servicos-ia'
    | '/sicaf'
    | '/suporte'
    | '/admin/alertas'
    | '/admin/atendimento'
    | '/admin/auditoria'
    | '/admin/automacoes'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/documentos'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/funil'
    | '/admin/google-ads'
    | '/admin/ia'
    | '/admin/perfis'
    | '/admin/relatorios'
    | '/admin/sicaf'
    | '/admin/suporte'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/assistente'
    | '/certidoes'
    | '/colaboradores'
    | '/concluido'
    | '/documentos'
    | '/empresas'
    | '/faltam'
    | '/licitacoes'
    | '/login'
    | '/missoes'
    | '/notificacoes'
    | '/pagamentos'
    | '/pagamentos_naoefetuado'
    | '/prontidao'
    | '/servicos'
    | '/servicos-ia'
    | '/sicaf'
    | '/suporte'
    | '/admin/alertas'
    | '/admin/atendimento'
    | '/admin/auditoria'
    | '/admin/automacoes'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/documentos'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/funil'
    | '/admin/google-ads'
    | '/admin/ia'
    | '/admin/perfis'
    | '/admin/relatorios'
    | '/admin/sicaf'
    | '/admin/suporte'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  AssistenteRoute: typeof AssistenteRoute
  CertidoesRoute: typeof CertidoesRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  ConcluidoRoute: typeof ConcluidoRoute
  DocumentosRoute: typeof DocumentosRoute
  EmpresasRoute: typeof EmpresasRoute
  FaltamRoute: typeof FaltamRoute
  LicitacoesRoute: typeof LicitacoesRoute
  LoginRoute: typeof LoginRoute
  MissoesRoute: typeof MissoesRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PagamentosRoute: typeof PagamentosRoute
  Pagamentos_naoefetuadoRoute: typeof Pagamentos_naoefetuadoRoute
  ProntidaoRoute: typeof ProntidaoRoute
  ServicosRoute: typeof ServicosRoute
  ServicosIaRoute: typeof ServicosIaRoute
  SicafRoute: typeof SicafRoute
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sicaf': {
      id: '/sicaf'
      path: '/sicaf'
      fullPath: '/sicaf'
      preLoaderRoute: typeof SicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos-ia': {
      id: '/servicos-ia'
      path: '/servicos-ia'
      fullPath: '/servicos-ia'
      preLoaderRoute: typeof ServicosIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prontidao': {
      id: '/prontidao'
      path: '/prontidao'
      fullPath: '/prontidao'
      preLoaderRoute: typeof ProntidaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos_naoefetuado': {
      id: '/pagamentos_naoefetuado'
      path: '/pagamentos_naoefetuado'
      fullPath: '/pagamentos_naoefetuado'
      preLoaderRoute: typeof Pagamentos_naoefetuadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes': {
      id: '/licitacoes'
      path: '/licitacoes'
      fullPath: '/licitacoes'
      preLoaderRoute: typeof LicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faltam': {
      id: '/faltam'
      path: '/faltam'
      fullPath: '/faltam'
      preLoaderRoute: typeof FaltamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concluido': {
      id: '/concluido'
      path: '/concluido'
      fullPath: '/concluido'
      preLoaderRoute: typeof ConcluidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certidoes': {
      id: '/certidoes'
      path: '/certidoes'
      fullPath: '/certidoes'
      preLoaderRoute: typeof CertidoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sicaf': {
      id: '/admin/sicaf'
      path: '/sicaf'
      fullPath: '/admin/sicaf'
      preLoaderRoute: typeof AdminSicafRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfis': {
      id: '/admin/perfis'
      path: '/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AdminPerfisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/google-ads': {
      id: '/admin/google-ads'
      path: '/google-ads'
      fullPath: '/admin/google-ads'
      preLoaderRoute: typeof AdminGoogleAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/funil': {
      id: '/admin/funil'
      path: '/funil'
      fullPath: '/admin/funil'
      preLoaderRoute: typeof AdminFunilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documentos': {
      id: '/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AdminDocumentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automacoes': {
      id: '/admin/automacoes'
      path: '/automacoes'
      fullPath: '/admin/automacoes'
      preLoaderRoute: typeof AdminAutomacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atendimento': {
      id: '/admin/atendimento'
      path: '/atendimento'
      fullPath: '/admin/atendimento'
      preLoaderRoute: typeof AdminAtendimentoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alertas': {
      id: '/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAlertasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertasRoute: typeof AdminAlertasRoute
  AdminAtendimentoRoute: typeof AdminAtendimentoRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminAutomacoesRoute: typeof AdminAutomacoesRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDocumentosRoute: typeof AdminDocumentosRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminFunilRoute: typeof AdminFunilRoute
  AdminGoogleAdsRoute: typeof AdminGoogleAdsRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminPerfisRoute: typeof AdminPerfisRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSicafRoute: typeof AdminSicafRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertasRoute: AdminAlertasRoute,
  AdminAtendimentoRoute: AdminAtendimentoRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminAutomacoesRoute: AdminAutomacoesRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDocumentosRoute: AdminDocumentosRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminFunilRoute: AdminFunilRoute,
  AdminGoogleAdsRoute: AdminGoogleAdsRoute,
  AdminIaRoute: AdminIaRoute,
  AdminPerfisRoute: AdminPerfisRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSicafRoute: AdminSicafRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AjudaRoute: AjudaRoute,
  AssistenteRoute: AssistenteRoute,
  CertidoesRoute: CertidoesRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  ConcluidoRoute: ConcluidoRoute,
  DocumentosRoute: DocumentosRoute,
  EmpresasRoute: EmpresasRoute,
  FaltamRoute: FaltamRoute,
  LicitacoesRoute: LicitacoesRoute,
  LoginRoute: LoginRoute,
  MissoesRoute: MissoesRoute,
  NotificacoesRoute: NotificacoesRoute,
  PagamentosRoute: PagamentosRoute,
  Pagamentos_naoefetuadoRoute: Pagamentos_naoefetuadoRoute,
  ProntidaoRoute: ProntidaoRoute,
  ServicosRoute: ServicosRoute,
  ServicosIaRoute: ServicosIaRoute,
  SicafRoute: SicafRoute,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
